### ISSUE TITLE
Getting SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by KBO2** [derekpankaew/IDEX-Market-Making-Bot#2]
Dear Derekpankaew and other,

When i setup the settings file and try to run I get the following error. I tried 2 different tokens.
Does anybody have any idea why this happens?

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)

**Comment by yukihirai0505** [comment]
I think it is better to stop using this.
This is an awful bot...
